import test from 'node:test';
import assert from 'node:assert/strict';
import {createHandler,validatePayload,submissionMetadata} from '../supabase/functions/assessment-api/index.ts';
const id='f47ac10b-58cc-4372-a567-0e02b2c3d479',account='550e8400-e29b-41d4-a716-446655440000',other='550e8400-e29b-41d4-a716-446655440001',submission='550e8400-e29b-41d4-a716-446655440002';
const token='stu_'+'a'.repeat(96),admin='adm_'+'b'.repeat(96),now=Date.parse('2026-09-13T12:00:00Z');
const item={id,kind:'assessment',unit_id:'unit3_eval',lesson_id:'u3e_l3',published:true,student_access:true,version:1};
const session={account_id:account,account_type:'student',session_type:'student',login_id:'20301',expires_at:'2026-09-13T13:00:00Z'};
const user={id:account,login_id:'20301',name:'Synthetic student',account_type:'student',status:'등록완료',school_year:2026};
const locks={evalHallVisibilityMode:'all',unit3_eval:{isLocked:false,lessons:{u3e_l3:false}}};
const env=key=>({SUPABASE_URL:'https://rerykeslgwhamreoskgx.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'test-placeholder-only'})[key];
function db(overrides={}){return{async one(table){if(table==='app_sessions')return session;if(table==='app_users')return user;if(table==='app_settings')return{setting_value:locks};if(table==='content_items')return item;if(table==='assessment_submissions'||table==='assessment_runtime_settings')return null;throw Error('Unexpected table '+table);},async request(path){if(path==='assessment_submissions'||path==='assessment_resubmit_permissions')return[];if(path==='rpc/assessment_submit_atomic')return{id:submission,revision:1,filename:'2301_student_v1.json'};throw Error('Unexpected request '+path);},...overrides};}
async function call(values,store=db()){const r=await createHandler({env,now:()=>now,store})(new Request('https://example.test',{method:'POST',headers:{'Content-Type':'application/json',Origin:'https://chemtea.github.io'},body:JSON.stringify(values)}));return{status:r.status,data:await r.json()};}
test('assessment anonymous cannot read status or submit',async()=>{for(const action of ['status','submit','get_submission'])assert.equal((await call({action,id,submission_id:submission})).status,401);});
test('assessment student cannot list classmates or grant resubmission',async()=>{for(const action of ['list_submissions','set_resubmit'])assert.equal((await call({action,id,studentSessionToken:token,account_id:other,slot:'data',allowed:true})).status,403);});
test('assessment get_submission denies another student without returning file or payload',async()=>{const store=db();const previous=store.one;store.one=async table=>table==='assessment_submissions'?{id:submission,account_id:other,slot:'pdf',storage_path:'private'}:previous(table);const r=await call({action:'get_submission',submission_id:submission,studentSessionToken:token},store);assert.equal(r.status,404);assert.equal('file_base64' in r.data,false);});
test('assessment status uses server profile and exposes no storage path or request token',async()=>{const r=await call({action:'status',id,studentSessionToken:token,studentId:'9999',name:'forged'});assert.equal(r.status,200);assert.equal(r.data.student.studentId,'2301');assert.equal(r.data.student.name,'Synthetic student');const safe=submissionMetadata({id,storage_path:'private',payload:{secret:true},payload_hash:'hash',request_id:'retry'});for(const k of ['storage_path','payload','payload_hash','request_id'])assert.equal(k in safe,false);});
test('assessment lock is enforced before any file is written',async()=>{const store=db();const old=store.one;store.one=async table=>table==='app_settings'?{setting_value:{}}:old(table);store.storage=()=>assert.fail('Locked request wrote file');const r=await call({action:'submit',id,slot:'pdf',content_version:1,request_id:submission,file_base64:btoa('%PDF-1.7 test'),studentSessionToken:token},store);assert.equal(r.status,403);});
test('assessment forged account identity never reaches atomic submission',async()=>{const store=db();let captured;store.request=async(path,q,body)=>{assert.equal(path,'rpc/assessment_submit_atomic');captured=body.p_submission;return{id:submission,revision:1};};const r=await call({action:'submit',id,slot:'data',content_version:1,request_id:submission,payload:{fields:{hypothesis:'test'}},account_id:other,studentSessionToken:token},store);assert.equal(r.status,200);assert.equal(captured.account_id,account);assert.match(captured.payload_hash,/^[0-9a-f]{64}$/);assert.equal(captured.storage_path,null);});
test('assessment stale versions and changed retry payloads fail',async()=>{const stale=await call({action:'submit',id,slot:'data',content_version:2,request_id:submission,payload:{a:1},studentSessionToken:token});assert.equal(stale.status,409);const store=db(),old=store.one;store.one=async table=>table==='assessment_submissions'?{id:submission,account_id:account,content_id:id,slot:'data',payload_hash:'different'}:old(table);assert.equal((await call({action:'submit',id,slot:'data',content_version:1,request_id:submission,payload:{a:1},studentSessionToken:token},store)).status,409);});
test('assessment arbitrary nested credential/prototype or oversized data rejected',()=>{for(const input of [null,[],JSON.parse('{"__proto__":{}}'),{a:{studentSessionToken:'secret'}},{text:'x'.repeat(524289)}])assert.throws(()=>validatePayload(input));assert.deepEqual(validatePayload({logs:[{voltage:6,current:1.2}]}),{logs:[{voltage:6,current:1.2}]});});
test('assessment private PDF is returned only for the current account',async()=>{const store=db(),old=store.one;store.one=async table=>table==='assessment_submissions'?{id:submission,account_id:account,slot:'pdf',storage_path:id+'/'+submission+'.pdf'}:old(table);store.storage=async path=>{assert.equal(path,id+'/'+submission+'.pdf');return new TextEncoder().encode('%PDF-1.7 own file');};const r=await call({action:'get_submission',submission_id:submission,studentSessionToken:token},store);assert.equal(r.status,200);assert.equal(atob(r.data.file_base64),'%PDF-1.7 own file');assert.equal('storage_path' in r.data.submission,false);});
